### ISSUE TITLE
Cross equation restrictions of parameters in ParameterizedFunctions

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/ParameterizedFunctions.jl#9] opened 2016-11-24 12:58 UTC
In parameterizedFunction, is it possible to have cross equation restrictions of parameters and functions of parameters in front of a variable? 

Also what is the most congenial way to write a system? 
F(Dy1, Dy2...y1, y2) =0 or
 
Dy1 = Dy2, Y1, Y2
Dy2 =  Dy2, Y1, Y2

Where is the best docs on ways of formulating a problem with ParameterizedFunctions?

**Comment by ChrisRackauckas** [comment] 2016-11-24 13:42
You currently cannot do that. When you mix derivatives like that, it's potentially a DAE. That's on the list: https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/5 but the algorithm has to get a lot more sophisticated to handle it.

**Comment by ChrisRackauckas** [comment] 2016-11-24 13:42
Closed as a duplicate of #5.

**Closed by ChrisRackauckas** 2016-11-24 13:42 UTC
