### ISSUE TITLE
Is there a way to know how many times a function defined as Macro is called ?

### ISSUE THREAD

**Issue by rohith14** [JuliaDiffEq/ParameterizedFunctions.jl#32] opened 2017-10-10 15:28 UTC
f = @ode_def LotkaVolterra begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1

If my solver calls this function, is there a way to see how many times 'f' is called ?

Thanks

**Comment by ChrisRackauckas** [comment] 2017-10-10 15:29
No there is not. It's a planned feature though (https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/54). If you instead use a regular function you can make it a call-overloaded type with an internal counter.

**Comment by rohith14** [comment] 2017-10-11 17:31
Thank you, Chris.  That worked

**Comment by ChrisRackauckas** [comment] 2017-10-12 18:26
For the more general case, closing this as a duplicate of JuliaDiffEq/DiffEqBase.jl#54

**Closed by ChrisRackauckas** 2017-10-12 18:26 UTC
