### ISSUE TITLE
Strange bug when using `@ode_def` in worker process on 0.7

### ISSUE THREAD

**Issue by jlumpe** [JuliaDiffEq/ParameterizedFunctions.jl#48] opened 2018-12-29 05:19 UTC
I'm getting a strange problem when trying to use a model defined with `@ode_def` within a worker process on Julia 0.7 only (no issues in 1.0). I've managed to strip it down to the following reproducible example:

Contents of `model.jl`:
```julia
using ParameterizedFunctions
model = @ode_def MyModel begin
        dX = -a * Y
        dY = b * X
end a b
```

Contents of `test.jl`:
```julia
using Distributed
addprocs(1)

@everywhere include("model2.jl")

@show model([1., 2.], [3., 4.], 0.)
@show @fetch model([1., 2.], [3., 4.], 0.)
```

All this does is try to evaluate the model function once in the main process and once in the worker process. Running with Julia 1.0.2 gives the expected output:

```
model([1.0, 2.0], [3.0, 4.0], 0.0) = [-6.0, 4.0]
#= /home/me/stuff/test.jl:9 =# @fetch(model([1.0, 2.0], [3.0, 4.0], 0.0)) = [-6.0, 4.0]
```

However with 0.7 I get the following warning:

```
model([1.0, 2.0], [3.0, 4.0], 0.0) = [-6.0, 4.0]
┌ Warning: `finalizer(o, f::Function)` is deprecated, use `finalizer(f, o)` instead.
│   caller = serialize_global_from_main(::Distributed.ClusterSerializer{Sockets.TCPSocket}, ::Symbol) at clusterserialize.jl:154
└ @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Distributed/src/clusterserialize.jl:154
┌ Warning: `finalizer(o, f::Function)` is deprecated, use `finalizer(f, o)` instead.
│   caller = finalizer(::Function, ::Function) at deprecated.jl:55
└ @ Base ./deprecated.jl:55
```

The main process then locks up at 100% cpu (0% on worker) and needs to be terminated.

I am using ParameterizedFunctions.jl v4.0.0 with Julia 1.0 and v3.10.0 with 0.7.

**Comment by jlumpe** [comment] 2018-12-29 16:09
Yes, sorry wasn't super clear about that.

**Comment by ChrisRackauckas** [comment] 2018-12-29 19:42
It sounds like a versioning issue, and it would be hard to track down what's up though. You can probably fix it by checking out the right versions of some dependencies. Likely the issue is the version of SymEngine.jl which updated after we had transitioned to v1.0, but we didn't have an upper bound on it and it was a breaking change. 

I am going to close this though, not trying to be mean, but I think that given our current manpower trying to keep v0.7 perfect is something we need to cut out of our maintenance duties. v0.7 was only intended as a short term update time, so we had it working but these days all of the packages require v1.0+. If you need help updating your v0.6 code to Julia v1.0 we can help you in the chat channel, but it shouldn't be too difficult for DiffEq code since the DiffEq syntax didn't change in that transition (which is why we did the transition so fast). Sorry if that's not the answer you were looking for, but I think that at this point actually fixing the v0.7 release would be a lot more pain than it's worth. But if you dig into it and find out which dependencies need the upper bound, I would be happy to help add those bounds to METADATA to fix the release.

**Closed by ChrisRackauckas** 2018-12-29 19:42 UTC

**Comment by jlumpe** [comment] 2018-12-30 21:43
Understood. I've been using 0.7 only because of some issues with PyJulia and 1.0 but I've been finding ways around them, making this less of an issue for me as well.

**Comment by ChrisRackauckas** [comment] 2019-01-03 10:19
As of very recently (last week?), diffeqpy tests are passing on v1.0, so it should be good? I don't know about other uses of it. If you had your own PyJulia cod, then yeah it makes sense because the diffeqpy upgrade required some changes.
